import path from 'path';
import fs from 'fs/promises';
import JSZip from 'jszip';
import { renderPortfolioToHtml, generateCss } from '../renderers/html.renderer';
import type { Portfolio } from '@devfolio/shared';

export interface ExportResult {
  fileUrl: string;
  filePath: string;
  sizeByes: number;
}

const UPLOADS_DIR = process.env.STORAGE_LOCAL_PATH ?? path.join(process.cwd(), 'uploads');

export async function processExport(
  portfolio: Portfolio,
  jobId: string,
): Promise<ExportResult> {
  // Ensure uploads directory exists
  await fs.mkdir(UPLOADS_DIR, { recursive: true });

  // Render HTML + CSS
  const { html, configJson } = renderPortfolioToHtml(portfolio);
  const css = generateCss(portfolio);

  // Build ZIP
  const zip = new JSZip();
  zip.file('index.html', html);
  zip.file('styles.css', css);
  zip.file('config.json', configJson);

  // README inside the ZIP
  zip.file(
    'README.md',
    `# ${portfolio.metadata.title ?? portfolio.slug} — Portfolio Export\n\n` +
    `Generated by [DevFolio](https://devfolio.app) on ${new Date().toISOString()}\n\n` +
    `## Deployment\n\n` +
    `Upload the contents of this ZIP to any static hosting provider:\n` +
    `- Netlify: drag & drop the folder\n` +
    `- Vercel: \`vercel --prod\`\n` +
    `- GitHub Pages: push to \`gh-pages\` branch\n` +
    `- Any web server: copy files to public directory\n`,
  );

  const zipBuffer = await zip.generateAsync({
    type: 'nodebuffer',
    compression: 'DEFLATE',
    compressionOptions: { level: 9 },
  });

  const fileName = `portfolio-${portfolio.slug}-${jobId}.zip`;
  const filePath = path.join(UPLOADS_DIR, fileName);
  await fs.writeFile(filePath, zipBuffer);

  const fileUrl = `/api/v1/exports/download/${fileName}`;

  return { fileUrl, filePath, sizeByes: zipBuffer.length };
}
