import type { ResumeTheme } from '@devfolio/shared';

export interface ResumePreset {
  id: string;
  name: string;
  description: string;
  colors: string[];   // accent, bg hint
  theme: Partial<ResumeTheme>;
}

export const RESUME_PRESETS: ResumePreset[] = [
  {
    id: 'classic-blue',
    name: 'Classic',
    description: 'Traditional & ATS-safe',
    colors: ['#1d4ed8', '#eff6ff'],
    theme: {
      template: 'classic',
      accent: '#1d4ed8',
      font: 'inter',
      fontSize: 11.5,
      lineHeight: 1.55,
      marginH: 52,
      marginV: 48,
      entrySpacing: 11,
      headingStyle: 'underline',
      headingSize: 's',
      headingCase: 'uppercase',
      headingAlign: 'left',
    },
  },
  {
    id: 'modern-violet',
    name: 'Modern',
    description: 'Bold and contemporary',
    colors: ['#7c3aed', '#f5f3ff'],
    theme: {
      template: 'modern',
      accent: '#7c3aed',
      font: 'inter',
      fontSize: 11.5,
      lineHeight: 1.6,
      marginH: 48,
      marginV: 44,
      entrySpacing: 12,
      headingStyle: 'leftbar',
      headingSize: 's',
      headingCase: 'uppercase',
      headingAlign: 'left',
    },
  },
  {
    id: 'minimal-gray',
    name: 'Minimal',
    description: 'Clean whitespace-first',
    colors: ['#374151', '#f9fafb'],
    theme: {
      template: 'minimal',
      accent: '#374151',
      font: 'lato',
      fontSize: 11.5,
      lineHeight: 1.65,
      marginH: 56,
      marginV: 52,
      entrySpacing: 13,
      headingStyle: 'simple',
      headingSize: 's',
      headingCase: 'capitalize',
      headingAlign: 'left',
    },
  },
  {
    id: 'executive',
    name: 'Executive',
    description: 'Senior & leadership roles',
    colors: ['#991b1b', '#fff7f7'],
    theme: {
      template: 'classic',
      accent: '#991b1b',
      font: 'playfair',
      fontSize: 12,
      lineHeight: 1.6,
      marginH: 56,
      marginV: 52,
      entrySpacing: 13,
      headingStyle: 'overline',
      headingSize: 'm',
      headingCase: 'capitalize',
      headingAlign: 'left',
    },
  },
  {
    id: 'tech-teal',
    name: 'Technical',
    description: 'Built for engineers',
    colors: ['#0891b2', '#f0fdff'],
    theme: {
      template: 'modern',
      accent: '#0891b2',
      font: 'jetbrains',
      fontSize: 10.5,
      lineHeight: 1.6,
      marginH: 44,
      marginV: 40,
      entrySpacing: 10,
      headingStyle: 'filled',
      headingSize: 'xs',
      headingCase: 'uppercase',
      headingAlign: 'left',
    },
  },
  {
    id: 'creative-pink',
    name: 'Creative',
    description: 'Stand out visually',
    colors: ['#be185d', '#fdf2f8'],
    theme: {
      template: 'minimal',
      accent: '#be185d',
      font: 'raleway',
      fontSize: 11.5,
      lineHeight: 1.7,
      marginH: 52,
      marginV: 48,
      entrySpacing: 14,
      headingStyle: 'double',
      headingSize: 'm',
      headingCase: 'capitalize',
      headingAlign: 'left',
    },
  },
];
